name: android-publish

on: workflow_dispatch

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      #- name: Setup java
      #  uses: actions/setup-java@v1
      #  with:
      #    java-version: 1.8

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18
          cache: 'npm'
      - name: Install Cordova
        run: npm install -g cordova
  
      - name: Install Ionic
        run: npm install -g @ionic/cli

      - name: Install app dependencies
        run: npm install
  #android_publish:
      #needs: ionic_build

      
