name: android-publish

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Repo Checkout
      uses: actions/checkout@v4
    - name: Install Ionic Cli
      run: |
        npm i -g ionic/cli
    - name: Install Ionic Cli
      run: |
        npm i -g ionic/cli
        npm i --legacy-peer-deps
        npm run build
        npx cap sync
  #android_publish:
      #needs: ionic_build

      
