name: android-publish

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ionic-build.yml
  #android_publish:
      #needs: ionic_build

      
