name: android-publish

on: workflow_dispatch

#TODO: aggiungere keystore nei secrets e crearlo nella cartella android con la action
#TODO: aggiungere i settings del file gradle.build nei secrets e aggiungere i valori nel file gradle.build nella action
#TODO: push su intune

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install app dependencies
        run: npm install
      - name: Install Ionic
        run: npm install -g @ionic/cli
      - name: Build
        run: npm run build
      - name: Cap sync
        run: npx cap sync
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
            java-version: '21'
            distribution: 'oracle'
      - name: Publish app
        run: |
          cd android
          ./gradlew assembleRelease
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: apk-signed-release
          path: ./android/app/build/outputs/apk/release/app-release.apk


