name: android-publish

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Repo Checkout
      uses: actions/checkout@v4
    - name: Ionic build
      uses: ./.github/workflows/ionic-build.yml
  #android_publish:
      #needs: ionic_build

      
