name: Ionic-Build
on: workflow_call
jobs:
  ionic_build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Ionic Cli
        run: |
          npm i -g ionic/cli
      - name: Install Ionic Cli
        run: |
          npm i -g ionic/cli
          npm i --legacy-peer-deps
          npm run build
          npx cap sync