name: sample-gitversion

on: workflow_dispatch

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # this makes the checkout action fetch the complete history

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.11
        with:
          versionSpec: '5.x'
 
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      
      - name: Install capacitor-set-version
        run: npm install -D capacitor-set-version  

      - name: Use GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.11
        with:
          useConfigFile: true
          configFilePath: 'build/GitVersion.yml'

      #  compute unique integer build code for android as "NOW(unix ts seconds) - 2024-05-01:00:00:00 UTC"
      - name: Compute Android Integer Build Code
        run: echo "BUILD_INT_VERSION_CODE=$(( $(date +%s) - 1714514400 ))" >> $GITHUB_ENV

      - name: Echo Version Number
        run: |
          echo "Version number is: ${{ steps.gitversion.outputs.majorMinorPatch }} and Android integer version code ${{ env.BUILD_INT_VERSION_CODE }}"

      - name: Update Workflow Run Name
        continue-on-error: true
        run: echo "::set-env name=run-name::Build and push ${{ steps.gitversion.outputs.majorMinorPatch }}"

      - name: Set up Git user
        run: |
          git config --local user.email "m.mezzanotte@ptsclas.com"
          git config --local user.name "Marco Mezzanotte through action"

      - name: Create and Push Tag
        continue-on-error: true
        run: |
          git tag v${{ steps.gitversion.outputs.majorMinorPatch }}
          git tag build-${{ env.BUILD_INT_VERSION_CODE }}
          git push origin --tags

      - name: Update package.json version
        run: |
          npm version $version --no-git-tag-version

      - name: Set Android app version code
        run: |
          npx capacitor-set-version set:android -v ${{ steps.gitversion.outputs.majorMinorPatch }} -b ${{ env.BUILD_INT_VERSION_CODE }}

      - name: Set iOS app version number
        run: |
          npx capacitor-set-version set:ios -v ${{ steps.gitversion.outputs.majorMinorPatch }} -b ${{ env.BUILD_INT_VERSION_CODE }}

      - name: Remove node_modules
        run: |
          find . -name "node_modules" -type d -prune -exec rm -rf '{}' +

      - name: Archive code
        run: |
          mkdir build-stage
          rsync -a --exclude=build-stage . build-stage/
          tar -czf source-code.tar.gz build-stage/

      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: prepared-code
          path: source-code.tar.gz

  android:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: prepared-code
      
      - name: Extract code
        run: tar -xzf .\source-code.tar.gz --strip-components=1 -C . build-stage/
        
        # actual build from here on
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install app dependencies
        run: npm install
      - name: Install Ionic
        run: npm install -g @ionic/cli
      - name: Build
        run: npm run build
      - name: Cap sync
        run: npx cap sync
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
            java-version: '21'
            distribution: 'oracle'
      - name: Publish app
        run: |
          cd android
          ./gradlew assembleRelease
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: apk-signed-release
          path: ./android/app/build/outputs/apk/release/app-release.apk

  ios:
    needs: prepare
    runs-on: macos-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: prepared-code

      - name: Extract code
        run: tar -xzf .\source-code.tar.gz --strip-components=1 -C . build-stage/
